[[redirects]]
  from = "/api/*"
  to = "https://brain-forge.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "client"
  publish = "dist"
  command = "npm run build"
